spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: postgres
    password: postgres
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
jwt:
  secret: apple
