spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musicdb;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /db-console
      settings:
        web-allow-others: false
  security:
    user:
      name: user
      password: 123
server:
  port: 8080