server:
  port: 8189
  servlet:
    context-path: /music
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: postgresql://localhost:5432/mydb
    username: Evengarr
    password: pass
    driver-class-name: org.postgresql.Driver
